// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        (unknown)
// source: simple/v1/simple.proto

package simplev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Idea struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name        string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category    string `protobuf:"bytes,2,opt,name=category,proto3" json:"category,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *Idea) Reset() {
	*x = Idea{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Idea) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Idea) ProtoMessage() {}

func (x *Idea) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Idea.ProtoReflect.Descriptor instead.
func (*Idea) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{0}
}

func (x *Idea) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Idea) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *Idea) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetIdeaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetIdeaRequest) Reset() {
	*x = GetIdeaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIdeaRequest) ProtoMessage() {}

func (x *GetIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIdeaRequest.ProtoReflect.Descriptor instead.
func (*GetIdeaRequest) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{1}
}

func (x *GetIdeaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateIdeaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idea *Idea `protobuf:"bytes,1,opt,name=idea,proto3" json:"idea,omitempty"`
}

func (x *CreateIdeaRequest) Reset() {
	*x = CreateIdeaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateIdeaRequest) ProtoMessage() {}

func (x *CreateIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateIdeaRequest.ProtoReflect.Descriptor instead.
func (*CreateIdeaRequest) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{2}
}

func (x *CreateIdeaRequest) GetIdea() *Idea {
	if x != nil {
		return x.Idea
	}
	return nil
}

type ListIdeasRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListIdeasRequest) Reset() {
	*x = ListIdeasRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIdeasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdeasRequest) ProtoMessage() {}

func (x *ListIdeasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdeasRequest.ProtoReflect.Descriptor instead.
func (*ListIdeasRequest) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{3}
}

type ListIdeasResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ideas []*Idea `protobuf:"bytes,1,rep,name=ideas,proto3" json:"ideas,omitempty"`
}

func (x *ListIdeasResponse) Reset() {
	*x = ListIdeasResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListIdeasResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListIdeasResponse) ProtoMessage() {}

func (x *ListIdeasResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListIdeasResponse.ProtoReflect.Descriptor instead.
func (*ListIdeasResponse) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{4}
}

func (x *ListIdeasResponse) GetIdeas() []*Idea {
	if x != nil {
		return x.Ideas
	}
	return nil
}

type DeleteIdeaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *DeleteIdeaRequest) Reset() {
	*x = DeleteIdeaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdeaRequest) ProtoMessage() {}

func (x *DeleteIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdeaRequest.ProtoReflect.Descriptor instead.
func (*DeleteIdeaRequest) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteIdeaRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DeleteIdeaResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteIdeaResponse) Reset() {
	*x = DeleteIdeaResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteIdeaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteIdeaResponse) ProtoMessage() {}

func (x *DeleteIdeaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteIdeaResponse.ProtoReflect.Descriptor instead.
func (*DeleteIdeaResponse) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{6}
}

type UpdateIdeaRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Idea *Idea `protobuf:"bytes,1,opt,name=idea,proto3" json:"idea,omitempty"`
}

func (x *UpdateIdeaRequest) Reset() {
	*x = UpdateIdeaRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_simple_v1_simple_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateIdeaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateIdeaRequest) ProtoMessage() {}

func (x *UpdateIdeaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_simple_v1_simple_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateIdeaRequest.ProtoReflect.Descriptor instead.
func (*UpdateIdeaRequest) Descriptor() ([]byte, []int) {
	return file_simple_v1_simple_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateIdeaRequest) GetIdea() *Idea {
	if x != nil {
		return x.Idea
	}
	return nil
}

var File_simple_v1_simple_proto protoreflect.FileDescriptor

var file_simple_v1_simple_proto_rawDesc = []byte{
	0x0a, 0x16, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65,
	0x2e, 0x76, 0x31, 0x22, 0x58, 0x0a, 0x04, 0x49, 0x64, 0x65, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x24, 0x0a,
	0x0e, 0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x22, 0x38, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65,
	0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x64, 0x65, 0x61,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x61, 0x52, 0x04, 0x69, 0x64, 0x65, 0x61, 0x22, 0x12, 0x0a,
	0x10, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x3a, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x05, 0x69, 0x64, 0x65, 0x61, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x49, 0x64, 0x65, 0x61, 0x52, 0x05, 0x69, 0x64, 0x65, 0x61, 0x73, 0x22, 0x27, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x14, 0x0a, 0x12, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x38, 0x0a, 0x11,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x23, 0x0a, 0x04, 0x69, 0x64, 0x65, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x61,
	0x52, 0x04, 0x69, 0x64, 0x65, 0x61, 0x32, 0xd3, 0x02, 0x0a, 0x0d, 0x53, 0x69, 0x6d, 0x70, 0x6c,
	0x65, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x35, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x49,
	0x64, 0x65, 0x61, 0x12, 0x19, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x47, 0x65, 0x74, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f,
	0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x61, 0x12,
	0x3b, 0x0a, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x12, 0x1c, 0x2e,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x61, 0x12, 0x46, 0x0a, 0x09,
	0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x12, 0x1b, 0x2e, 0x73, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x49, 0x64, 0x65, 0x61, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x49, 0x0a, 0x0a, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64,
	0x65, 0x61, 0x12, 0x1c, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1d, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x3b, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x49, 0x64, 0x65, 0x61, 0x12, 0x1c, 0x2e,
	0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x49, 0x64, 0x65, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0f, 0x2e, 0x73, 0x69,
	0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x49, 0x64, 0x65, 0x61, 0x42, 0x8f, 0x01, 0x0a,
	0x0d, 0x63, 0x6f, 0x6d, 0x2e, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x76, 0x31, 0x42, 0x0b,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x2c, 0x70,
	0x72, 0x65, 0x73, 0x65, 0x6e, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2f,
	0x76, 0x31, 0x3b, 0x73, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x53, 0x58,
	0x58, 0xaa, 0x02, 0x09, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x2e, 0x56, 0x31, 0xca, 0x02, 0x09,
	0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x15, 0x53, 0x69, 0x6d, 0x70,
	0x6c, 0x65, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0xea, 0x02, 0x0a, 0x53, 0x69, 0x6d, 0x70, 0x6c, 0x65, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_simple_v1_simple_proto_rawDescOnce sync.Once
	file_simple_v1_simple_proto_rawDescData = file_simple_v1_simple_proto_rawDesc
)

func file_simple_v1_simple_proto_rawDescGZIP() []byte {
	file_simple_v1_simple_proto_rawDescOnce.Do(func() {
		file_simple_v1_simple_proto_rawDescData = protoimpl.X.CompressGZIP(file_simple_v1_simple_proto_rawDescData)
	})
	return file_simple_v1_simple_proto_rawDescData
}

var file_simple_v1_simple_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_simple_v1_simple_proto_goTypes = []interface{}{
	(*Idea)(nil),               // 0: simple.v1.Idea
	(*GetIdeaRequest)(nil),     // 1: simple.v1.GetIdeaRequest
	(*CreateIdeaRequest)(nil),  // 2: simple.v1.CreateIdeaRequest
	(*ListIdeasRequest)(nil),   // 3: simple.v1.ListIdeasRequest
	(*ListIdeasResponse)(nil),  // 4: simple.v1.ListIdeasResponse
	(*DeleteIdeaRequest)(nil),  // 5: simple.v1.DeleteIdeaRequest
	(*DeleteIdeaResponse)(nil), // 6: simple.v1.DeleteIdeaResponse
	(*UpdateIdeaRequest)(nil),  // 7: simple.v1.UpdateIdeaRequest
}
var file_simple_v1_simple_proto_depIdxs = []int32{
	0, // 0: simple.v1.CreateIdeaRequest.idea:type_name -> simple.v1.Idea
	0, // 1: simple.v1.ListIdeasResponse.ideas:type_name -> simple.v1.Idea
	0, // 2: simple.v1.UpdateIdeaRequest.idea:type_name -> simple.v1.Idea
	1, // 3: simple.v1.SimpleService.GetIdea:input_type -> simple.v1.GetIdeaRequest
	2, // 4: simple.v1.SimpleService.CreateIdea:input_type -> simple.v1.CreateIdeaRequest
	3, // 5: simple.v1.SimpleService.ListIdeas:input_type -> simple.v1.ListIdeasRequest
	5, // 6: simple.v1.SimpleService.DeleteIdea:input_type -> simple.v1.DeleteIdeaRequest
	7, // 7: simple.v1.SimpleService.UpdateIdea:input_type -> simple.v1.UpdateIdeaRequest
	0, // 8: simple.v1.SimpleService.GetIdea:output_type -> simple.v1.Idea
	0, // 9: simple.v1.SimpleService.CreateIdea:output_type -> simple.v1.Idea
	4, // 10: simple.v1.SimpleService.ListIdeas:output_type -> simple.v1.ListIdeasResponse
	6, // 11: simple.v1.SimpleService.DeleteIdea:output_type -> simple.v1.DeleteIdeaResponse
	0, // 12: simple.v1.SimpleService.UpdateIdea:output_type -> simple.v1.Idea
	8, // [8:13] is the sub-list for method output_type
	3, // [3:8] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_simple_v1_simple_proto_init() }
func file_simple_v1_simple_proto_init() {
	if File_simple_v1_simple_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_simple_v1_simple_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Idea); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetIdeaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateIdeaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIdeasRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListIdeasResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIdeaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteIdeaResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_simple_v1_simple_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateIdeaRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_simple_v1_simple_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_simple_v1_simple_proto_goTypes,
		DependencyIndexes: file_simple_v1_simple_proto_depIdxs,
		MessageInfos:      file_simple_v1_simple_proto_msgTypes,
	}.Build()
	File_simple_v1_simple_proto = out.File
	file_simple_v1_simple_proto_rawDesc = nil
	file_simple_v1_simple_proto_goTypes = nil
	file_simple_v1_simple_proto_depIdxs = nil
}
